CREATE TABLE IF NOT EXISTS users (
    user_id int generated by default as identity primary key,
    user_name varchar(64),
    user_login varchar(64),
    user_password varchar(64)
);

CREATE TABLE IF NOT EXISTS items (
    item_id int generated by default as identity primary key,
    owner_id int,
    item_name varchar(64),
    item_description varchar(64),
    access_status varchar(64),
    CONSTRAINT fk_owner FOREIGN KEY(owner_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS requests (
    request_id int generated by default as identity primary key,
    user_id int,
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id int generated by default as identity primary key,
    user_id int,
    item_id int,
    booking_time timestamp,
    CONSTRAINT fk_owner FOREIGN KEY(user_id) REFERENCES users(user_id),
    CONSTRAINT fk_item FOREIGN KEY(item_id) REFERENCES items(item_id)
);

CREATE TABLE IF NOT EXISTS reviews (
    review_id int generated by default as identity primary key,
    review_text varchar(1024),
    user_id int,
    item_id int,
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(user_id),
    CONSTRAINT fk_item FOREIGN KEY(item_id) REFERENCES items(item_id)
);